version: '3'

services:
  db:
    image: postgres:9.6.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=youtube
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=youtube
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_USER=youtube
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=youtube
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_ENGINE=django.db.backends.postgresql_psycopg2
  celery:
    build: .
    command: celery -A youtube worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A youtube beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data: